name: release-please

on:
    push:
        branches: ["main"]

jobs:
    release-please:
        permissions:
            id-token: write
            contents: write
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4.1.6

            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.ACTIOPNS_TOKEN }}

            - name: Release Please Results
              env:
                  RESULTS: ${{ toJSON(steps.release.outputs) }}
              run: echo "$RESULTS"

            - name: build
            #   if: ${{ steps.release.outputs.release_created }}
              uses: ./.github/actions/build

            - name: Release Please Results
              env:
                  RESULTS: ${{ toJSON(steps.release.outputs) }}
              run: echo "$RESULTS"

            # - name: Upload Release Asset file
            #   uses: actions/upload-release-asset@v1
            #   if: ${{ steps.release.outputs.release_created }}
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.ACTIOPNS_TOKEN }}
            #   with:
            #       upload_url: ${{ steps.release.outputs.upload_url }}
            #       asset_path: ./dist.tar.xz
            #       asset_name: dist.tar.xz
            #       asset_content_type: application/octet-stream


            - name: create dist zip
              run: tar cvzf  dist.tar.xz package.json
