name: release-please

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    release-please:
        permissions:
            id-token: write
            contents: write
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4.1.6


            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: log pwd file list
              run: ls -l -a

            - name: Install dependencies
              run: npm i -g pnpm
            - run: pnpm i

            - name: build
              run: pnpm run build

            - name: create dist zip
              run: tar cvzf  dist.tar.xz .vitepress/dist/

            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.ACTIOPNS_TOKEN }}
                  path: /CHANGELOG.md

            - name: Upload Release Asset file
              if: steps.release.outputs.release_created == 'true'
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.release.outputs.upload_url }}
                  asset_path: dist.tar.xz
                  asset_name: your_binary_windows.exe
                  asset_content_type: application/octet-stream
